[package]
name = "fastdb"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
fastql-parser = { path = "../parser" }
turso_core = { path = "../../core" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["float_roundtrip"] }
thiserror.workspace = true
turso_parser = { path = "../../sqlite/parser" }
turso_ext = { path = "../../extensions/core" }

rquickjs = { version = "=0.12.2", default-features = false, features = ["std"] }
