<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>FastDB.Embedded</PackageId>
    <Version>2.0.0</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Native embedded FastDB and FastQL</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
    <None Include="../LICENSE.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
