[package]
name = "fastdb-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
fastdb = { path = "../frontend" }
fastql-parser = { path = "../parser" }
serde_json.workspace = true
rustyline = { version = "=15.0.0", default-features = false, features = ["with-file-history"] }

[target.'cfg(unix)'.dependencies]
signal-hook = "=0.3.18"
