class NativeCancellation:
    def __init__(self, timeout_ms: int | None = None) -> None: ...
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...

class NativeDatabase:
    def __init__(self, path: str, write_limits: str | None = None) -> None: ...
    def call(self, request: str, token: NativeCancellation) -> str: ...
    def interrupt(self) -> bool: ...
    def close(self) -> None: ...

def vector(encoding: str, components: list[float]) -> bytes: ...
